import { cleanText } from '../lib/http.mjs';
import { sanitizeImageUrl, suppressRepeatedImages } from '../lib/images.mjs';
import { isStoredArticleAllowed } from '../lib/sources.mjs';
import { getStore } from '@netlify/blobs';
const STORE='rapli-actu',PREFIX='history/day/',DAYS=30;
function normalizeArticleText(x){if(!x)return x;return {...x,title:cleanText(x.title||''),originalTitle:cleanText(x.originalTitle||''),summary:cleanText(x.summary||''),image:sanitizeImageUrl(x.image||'')}}
function daysBack(before){const end=new Date(before||Date.now());if(Number.isNaN(end.getTime()))end.setTime(Date.now());end.setUTCHours(0,0,0,0);const out=[];for(let i=0;i<DAYS;i++){const d=new Date(end);d.setUTCDate(d.getUTCDate()-i);out.push(d.toISOString().slice(0,10))}return out}
const time=x=>{const t=Date.parse(x?.publishedAt||x?.discoveredAt||0);return Number.isFinite(t)?t:0};
export default async request=>{const url=new URL(request.url),beforeRaw=url.searchParams.get('before')||new Date().toISOString();const before=Date.parse(beforeRaw);const limit=Math.max(20,Math.min(200,Number(url.searchParams.get('limit')||100)));const category=url.searchParams.get('category')||'all',source=url.searchParams.get('source')||'all';const store=getStore(STORE);const map=new Map();for(const day of daysBack(beforeRaw)){const arr=await store.get(`${PREFIX}${day}`,{type:'json',consistency:'strong'})||[];for(const x of arr){if(!isStoredArticleAllowed(x))continue;if(time(x)>=before)continue;if(category!=='all'&&x.category!==category)continue;if(source!=='all'&&x.sourceId!==source)continue;if(!map.has(x.id))map.set(x.id,x)}if(map.size>=limit*2)break}const all=[...map.values()].sort((a,b)=>time(b)-time(a));const articles=suppressRepeatedImages(all.slice(0,limit).map(normalizeArticleText));const oldest=articles.at(-1);const nextBefore=oldest?new Date(Math.max(0,time(oldest)-1)).toISOString():null;return Response.json({articles,nextBefore,hasMore:all.length>limit||!!oldest},{headers:{'cache-control':'public, max-age=60, stale-while-revalidate=300'}})};
export const config={path:'/api/history'};
