import { cleanText } from '../lib/http.mjs';
import { ACTIVE_SOURCE_IDS, isStoredArticleAllowed } from '../lib/sources.mjs';
import { getStore } from '@netlify/blobs';
const STORE='rapli-actu',CURRENT='feed/current',PREFIX='history/day/';
function normalizeArticleText(x){if(!x)return x;const{image,thumbnail,...rest}=x;return {...rest,title:cleanText(x.title||''),originalTitle:cleanText(x.originalTitle||''),summary:cleanText(x.summary||'')}}
function dayList(startIso){const start=new Date(startIso);if(Number.isNaN(start.getTime()))return[];const cutoff=new Date(Date.now()-30*86400000);if(start<cutoff)start.setTime(cutoff.getTime());start.setUTCHours(0,0,0,0);const end=new Date();end.setUTCHours(0,0,0,0);const out=[];for(let d=new Date(start);d<=end;d.setUTCDate(d.getUTCDate()+1))out.push(d.toISOString().slice(0,10));return out}
async function countSince(store,since){if(!since||Number.isNaN(Date.parse(since)))return 0;const threshold=Date.parse(since);const days=dayList(since);const pages=await Promise.all(days.map(day=>store.get(`${PREFIX}${day}`,{type:'json',consistency:'strong'}).catch(()=>[])));let count=0;for(const arr0 of pages){const arr=arr0||[];for(const x of arr)if(isStoredArticleAllowed(x)&&Date.parse(x.discoveredAt||0)>threshold)count++}return count}
export default async request=>{const store=getStore(STORE);const feed=await store.get(CURRENT,{type:'json',consistency:'strong'});if(!feed)return Response.json({version:'2.0.0',generatedAt:null,stats:{sources:0,ok:0,stale:0,errors:0,disabled:0,articles:0,newThisCycle:0},sources:[],articles:[],newCount:0,message:'Aucune collecte disponible. Lance collect une première fois.'},{status:200,headers:{'cache-control':'no-store'}});
  const url=new URL(request.url),since=url.searchParams.get('since');const newCount=await countSince(store,since);const filteredSources=(feed.sources||[]).filter(x=>ACTIVE_SOURCE_IDS.has(x.id));const filteredArticles=(feed.articles||[]).filter(x=>isStoredArticleAllowed(x)).map(normalizeArticleText);const body={...feed,sources:filteredSources,articles:filteredArticles,stats:{...(feed.stats||{}),sources:filteredSources.length,articles:filteredArticles.length},newCount};const etag=`W/\"${feed.generatedAt||'empty'}-${feed.stats?.articles||0}-${newCount}\"`;if(request.headers.get('if-none-match')===etag)return new Response(null,{status:304,headers:{etag}});return Response.json(body,{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=45, stale-while-revalidate=300','etag':etag,'x-rapli-generated-at':feed.generatedAt||''}})};
export const config={path:'/api/feed'};
